#!/usr/bin/env python3
"""scanify

Usage:
  scanify <path>
  scanify <path> -o <outpath>
Examples:
  scanify '/path/to/image.jpg'

Options:
  -o --out      output path of the image, default output to the same path with
                sufixx
"""

from core import *
from docopt import docopt


if __name__ == "__main__":
    runnable = Scanifier()
    options = docopt(__doc__, version='scanify 0.0.1')
    context_dict = {}
    in_path = options['<path>']
    out_path = options.get('<outpath>')

    runnable.run(in_path, out_path, True)